spring.application.name=inventory-engine

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_engine
spring.datasource.username=omnicore
spring.datasource.password=omnicore

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
